SCHEMA etr;
ENTITY super;
END_ENTITY;
ENTITY sub_1
SUBTYPE OF (super);
attr : from_ent;
END_ENTITY;
ENTITY sub_2
SUBTYPE OF (super);
pick : choice;
END_ENTITY;
ENTITY an_ent;
int : INTEGER;
END_ENTITY;
ENTITY from_ent;
description : OPTIONAL to_ent;
values : ARRAY [1:3] OF UNIQUE REAL;
END_ENTITY;
ENTITY to_ent;
text : strings;
END_ENTITY;


TYPE choice = SELECT
(an_ent,
name);
END_TYPE;
TYPE name = STRING;
END_TYPE;